CREATE TABLE IF NOT EXISTS media_assets (
    id UUID PRIMARY KEY,
    lesson_id UUID NOT NULL,
    type TEXT NOT NULL,
    status TEXT NOT NULL,
    raw_url TEXT NOT NULL,
    cdn_urls TEXT[],
    job_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
